//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for GeoJSONFeatureGeometryType.
const (
	Point GeoJSONFeatureGeometryType = "Point"
)

// Defines values for GeoJSONFeatureType.
const (
	Feature GeoJSONFeatureType = "Feature"
)

// Defines values for GeoJSONFeatureCollectionType.
const (
	FeatureCollection GeoJSONFeatureCollectionType = "FeatureCollection"
)

// Defines values for SourceType.
const (
	Archive SourceType = "archive"
	Article SourceType = "article"
	Book    SourceType = "book"
	Map     SourceType = "map"
	Photo   SourceType = "photo"
	Web     SourceType = "web"
)

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Event defines model for Event.
type Event struct {
	CreatedAt    time.Time           `json:"created_at"`
	DateFrom     openapi_types.Date  `json:"date_from"`
	DateTo       *openapi_types.Date `json:"date_to"`
	Description  *string             `json:"description,omitempty"`
	Id           int64               `json:"id"`
	Latitude     *float64            `json:"latitude"`
	LocationId   *int64              `json:"location_id"`
	LocationName string              `json:"location_name"`
	Longitude    *float64            `json:"longitude"`
	Tags         []string            `json:"tags"`
	Title        string              `json:"title"`
	UpdatedAt    time.Time           `json:"updated_at"`
}

// EventInput defines model for EventInput.
type EventInput struct {
	DateFrom    openapi_types.Date  `json:"date_from"`
	DateTo      *openapi_types.Date `json:"date_to"`
	Description *string             `json:"description,omitempty"`
	LocationId  *int64              `json:"location_id"`
	Tags        *[]string           `json:"tags,omitempty"`
	Title       string              `json:"title"`
}

// GeoJSONFeature defines model for GeoJSONFeature.
type GeoJSONFeature struct {
	Geometry struct {
		Coordinates []float32                  `json:"coordinates"`
		Type        GeoJSONFeatureGeometryType `json:"type"`
	} `json:"geometry"`
	Properties map[string]interface{} `json:"properties"`
	Type       GeoJSONFeatureType     `json:"type"`
}

// GeoJSONFeatureGeometryType defines model for GeoJSONFeature.Geometry.Type.
type GeoJSONFeatureGeometryType string

// GeoJSONFeatureType defines model for GeoJSONFeature.Type.
type GeoJSONFeatureType string

// GeoJSONFeatureCollection defines model for GeoJSONFeatureCollection.
type GeoJSONFeatureCollection struct {
	Features []GeoJSONFeature             `json:"features"`
	Type     GeoJSONFeatureCollectionType `json:"type"`
}

// GeoJSONFeatureCollectionType defines model for GeoJSONFeatureCollection.Type.
type GeoJSONFeatureCollectionType string

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// Location defines model for Location.
type Location struct {
	CreatedAt   time.Time `json:"created_at"`
	Description *string   `json:"description,omitempty"`
	Id          int64     `json:"id"`
	Latitude    float64   `json:"latitude"`
	Longitude   float64   `json:"longitude"`
	Name        string    `json:"name"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// LocationInput defines model for LocationInput.
type LocationInput struct {
	Description *string `json:"description,omitempty"`
	Latitude    float64 `json:"latitude"`
	Longitude   float64 `json:"longitude"`
	Name        string  `json:"name"`
}

// Media defines model for Media.
type Media struct {
	Caption *string `json:"caption,omitempty"`
	EventId int64   `json:"event_id"`
	Id      int64   `json:"id"`
	Type    *string `json:"type,omitempty"`
	Url     string  `json:"url"`
}

// MediaInput defines model for MediaInput.
type MediaInput struct {
	Caption *string `json:"caption,omitempty"`
	Type    *string `json:"type,omitempty"`
	Url     string  `json:"url"`
}

// Source defines model for Source.
type Source struct {
	Author *string     `json:"author,omitempty"`
	Id     int64       `json:"id"`
	Title  string      `json:"title"`
	Type   *SourceType `json:"type,omitempty"`
	Url    *string     `json:"url,omitempty"`
	Year   *int        `json:"year"`
}

// SourceInput defines model for SourceInput.
type SourceInput struct {
	Author *string     `json:"author,omitempty"`
	Title  string      `json:"title"`
	Type   *SourceType `json:"type,omitempty"`
	Url    *string     `json:"url,omitempty"`
	Year   *int        `json:"year"`
}

// SourceType defines model for SourceType.
type SourceType string

// Tag defines model for Tag.
type Tag struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

// TagInput defines model for TagInput.
type TagInput struct {
	Name string `json:"name"`
}

// ID defines model for ID.
type ID = int64

// GetApiEventsParams defines parameters for GetApiEvents.
type GetApiEventsParams struct {
	// From Start filter as YYYY or YYYY-MM-DD
	From *string `form:"from,omitempty" json:"from,omitempty"`

	// To End filter as YYYY or YYYY-MM-DD
	To  *string `form:"to,omitempty" json:"to,omitempty"`
	Tag *string `form:"tag,omitempty" json:"tag,omitempty"`

	// Q Case-insensitive search in title and description
	Q          *string `form:"q,omitempty" json:"q,omitempty"`
	LocationId *int64  `form:"location_id,omitempty" json:"location_id,omitempty"`
	Limit      *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetApiMapEventsGeojsonParams defines parameters for GetApiMapEventsGeojson.
type GetApiMapEventsGeojsonParams struct {
	From       *string `form:"from,omitempty" json:"from,omitempty"`
	To         *string `form:"to,omitempty" json:"to,omitempty"`
	Tag        *string `form:"tag,omitempty" json:"tag,omitempty"`
	Q          *string `form:"q,omitempty" json:"q,omitempty"`
	LocationId *int64  `form:"location_id,omitempty" json:"location_id,omitempty"`
	Limit      *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostApiEventsJSONRequestBody defines body for PostApiEvents for application/json ContentType.
type PostApiEventsJSONRequestBody = EventInput

// PutApiEventsIdJSONRequestBody defines body for PutApiEventsId for application/json ContentType.
type PutApiEventsIdJSONRequestBody = EventInput

// PostApiEventsIdMediaJSONRequestBody defines body for PostApiEventsIdMedia for application/json ContentType.
type PostApiEventsIdMediaJSONRequestBody = MediaInput

// PostApiLocationsJSONRequestBody defines body for PostApiLocations for application/json ContentType.
type PostApiLocationsJSONRequestBody = LocationInput

// PutApiLocationsIdJSONRequestBody defines body for PutApiLocationsId for application/json ContentType.
type PutApiLocationsIdJSONRequestBody = LocationInput

// PostApiSourcesJSONRequestBody defines body for PostApiSources for application/json ContentType.
type PostApiSourcesJSONRequestBody = SourceInput

// PutApiSourcesIdJSONRequestBody defines body for PutApiSourcesId for application/json ContentType.
type PutApiSourcesIdJSONRequestBody = SourceInput

// PostApiTagsJSONRequestBody defines body for PostApiTags for application/json ContentType.
type PostApiTagsJSONRequestBody = TagInput

// PutApiTagsIdJSONRequestBody defines body for PutApiTagsId for application/json ContentType.
type PutApiTagsIdJSONRequestBody = TagInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List events
	// (GET /api/events)
	GetApiEvents(w http.ResponseWriter, r *http.Request, params GetApiEventsParams)
	// Create an event
	// (POST /api/events)
	PostApiEvents(w http.ResponseWriter, r *http.Request)
	// Delete an event
	// (DELETE /api/events/{id})
	DeleteApiEventsId(w http.ResponseWriter, r *http.Request, id ID)
	// Get an event
	// (GET /api/events/{id})
	GetApiEventsId(w http.ResponseWriter, r *http.Request, id ID)
	// Update an event
	// (PUT /api/events/{id})
	PutApiEventsId(w http.ResponseWriter, r *http.Request, id ID)
	// List event media
	// (GET /api/events/{id}/media)
	GetApiEventsIdMedia(w http.ResponseWriter, r *http.Request, id ID)
	// Add media to an event
	// (POST /api/events/{id}/media)
	PostApiEventsIdMedia(w http.ResponseWriter, r *http.Request, id ID)
	// List sources linked to an event
	// (GET /api/events/{id}/sources)
	GetApiEventsIdSources(w http.ResponseWriter, r *http.Request, id ID)
	// Unlink a source from an event
	// (DELETE /api/events/{id}/sources/{source_id})
	DeleteApiEventsIdSourcesSourceId(w http.ResponseWriter, r *http.Request, id ID, sourceId int64)
	// Link a source to an event
	// (POST /api/events/{id}/sources/{source_id})
	PostApiEventsIdSourcesSourceId(w http.ResponseWriter, r *http.Request, id ID, sourceId int64)
	// List locations
	// (GET /api/locations)
	GetApiLocations(w http.ResponseWriter, r *http.Request)
	// Create a location
	// (POST /api/locations)
	PostApiLocations(w http.ResponseWriter, r *http.Request)
	// Delete a location
	// (DELETE /api/locations/{id})
	DeleteApiLocationsId(w http.ResponseWriter, r *http.Request, id ID)
	// Get a location
	// (GET /api/locations/{id})
	GetApiLocationsId(w http.ResponseWriter, r *http.Request, id ID)
	// Update a location
	// (PUT /api/locations/{id})
	PutApiLocationsId(w http.ResponseWriter, r *http.Request, id ID)
	// Get events as GeoJSON FeatureCollection
	// (GET /api/map/events.geojson)
	GetApiMapEventsGeojson(w http.ResponseWriter, r *http.Request, params GetApiMapEventsGeojsonParams)
	// Delete media
	// (DELETE /api/media/{id})
	DeleteApiMediaId(w http.ResponseWriter, r *http.Request, id ID)
	// List sources
	// (GET /api/sources)
	GetApiSources(w http.ResponseWriter, r *http.Request)
	// Create a source
	// (POST /api/sources)
	PostApiSources(w http.ResponseWriter, r *http.Request)
	// Delete a source
	// (DELETE /api/sources/{id})
	DeleteApiSourcesId(w http.ResponseWriter, r *http.Request, id ID)
	// Get a source
	// (GET /api/sources/{id})
	GetApiSourcesId(w http.ResponseWriter, r *http.Request, id ID)
	// Update a source
	// (PUT /api/sources/{id})
	PutApiSourcesId(w http.ResponseWriter, r *http.Request, id ID)
	// List tags
	// (GET /api/tags)
	GetApiTags(w http.ResponseWriter, r *http.Request)
	// Create or return a tag
	// (POST /api/tags)
	PostApiTags(w http.ResponseWriter, r *http.Request)
	// Delete a tag
	// (DELETE /api/tags/{id})
	DeleteApiTagsId(w http.ResponseWriter, r *http.Request, id ID)
	// Update a tag
	// (PUT /api/tags/{id})
	PutApiTagsId(w http.ResponseWriter, r *http.Request, id ID)
	// Check API and database availability
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetApiEvents operation middleware
func (siw *ServerInterfaceWrapper) GetApiEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiEventsParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", r.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameter("form", true, false, "to", r.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", r.URL.Query(), &params.Tag)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "location_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "location_id", r.URL.Query(), &params.LocationId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "location_id", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiEvents operation middleware
func (siw *ServerInterfaceWrapper) PostApiEvents(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiEvents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiEventsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiEventsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiEventsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiEventsId operation middleware
func (siw *ServerInterfaceWrapper) GetApiEventsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiEventsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutApiEventsId operation middleware
func (siw *ServerInterfaceWrapper) PutApiEventsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiEventsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiEventsIdMedia operation middleware
func (siw *ServerInterfaceWrapper) GetApiEventsIdMedia(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiEventsIdMedia(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiEventsIdMedia operation middleware
func (siw *ServerInterfaceWrapper) PostApiEventsIdMedia(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiEventsIdMedia(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiEventsIdSources operation middleware
func (siw *ServerInterfaceWrapper) GetApiEventsIdSources(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiEventsIdSources(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiEventsIdSourcesSourceId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiEventsIdSourcesSourceId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "source_id" -------------
	var sourceId int64

	err = runtime.BindStyledParameterWithOptions("simple", "source_id", r.PathValue("source_id"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiEventsIdSourcesSourceId(w, r, id, sourceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiEventsIdSourcesSourceId operation middleware
func (siw *ServerInterfaceWrapper) PostApiEventsIdSourcesSourceId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "source_id" -------------
	var sourceId int64

	err = runtime.BindStyledParameterWithOptions("simple", "source_id", r.PathValue("source_id"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiEventsIdSourcesSourceId(w, r, id, sourceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiLocations operation middleware
func (siw *ServerInterfaceWrapper) GetApiLocations(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiLocations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiLocations operation middleware
func (siw *ServerInterfaceWrapper) PostApiLocations(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiLocations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiLocationsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiLocationsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiLocationsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiLocationsId operation middleware
func (siw *ServerInterfaceWrapper) GetApiLocationsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiLocationsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutApiLocationsId operation middleware
func (siw *ServerInterfaceWrapper) PutApiLocationsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiLocationsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiMapEventsGeojson operation middleware
func (siw *ServerInterfaceWrapper) GetApiMapEventsGeojson(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiMapEventsGeojsonParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", r.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameter("form", true, false, "to", r.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", r.URL.Query(), &params.Tag)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "location_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "location_id", r.URL.Query(), &params.LocationId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "location_id", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiMapEventsGeojson(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiMediaId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiMediaId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiMediaId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiSources operation middleware
func (siw *ServerInterfaceWrapper) GetApiSources(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiSources(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiSources operation middleware
func (siw *ServerInterfaceWrapper) PostApiSources(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiSources(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiSourcesId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiSourcesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiSourcesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiSourcesId operation middleware
func (siw *ServerInterfaceWrapper) GetApiSourcesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiSourcesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutApiSourcesId operation middleware
func (siw *ServerInterfaceWrapper) PutApiSourcesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiSourcesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiTags operation middleware
func (siw *ServerInterfaceWrapper) GetApiTags(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiTags(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiTags operation middleware
func (siw *ServerInterfaceWrapper) PostApiTags(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiTags(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiTagsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiTagsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiTagsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutApiTagsId operation middleware
func (siw *ServerInterfaceWrapper) PutApiTagsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiTagsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/events", wrapper.GetApiEvents)
	m.HandleFunc("POST "+options.BaseURL+"/api/events", wrapper.PostApiEvents)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/events/{id}", wrapper.DeleteApiEventsId)
	m.HandleFunc("GET "+options.BaseURL+"/api/events/{id}", wrapper.GetApiEventsId)
	m.HandleFunc("PUT "+options.BaseURL+"/api/events/{id}", wrapper.PutApiEventsId)
	m.HandleFunc("GET "+options.BaseURL+"/api/events/{id}/media", wrapper.GetApiEventsIdMedia)
	m.HandleFunc("POST "+options.BaseURL+"/api/events/{id}/media", wrapper.PostApiEventsIdMedia)
	m.HandleFunc("GET "+options.BaseURL+"/api/events/{id}/sources", wrapper.GetApiEventsIdSources)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/events/{id}/sources/{source_id}", wrapper.DeleteApiEventsIdSourcesSourceId)
	m.HandleFunc("POST "+options.BaseURL+"/api/events/{id}/sources/{source_id}", wrapper.PostApiEventsIdSourcesSourceId)
	m.HandleFunc("GET "+options.BaseURL+"/api/locations", wrapper.GetApiLocations)
	m.HandleFunc("POST "+options.BaseURL+"/api/locations", wrapper.PostApiLocations)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/locations/{id}", wrapper.DeleteApiLocationsId)
	m.HandleFunc("GET "+options.BaseURL+"/api/locations/{id}", wrapper.GetApiLocationsId)
	m.HandleFunc("PUT "+options.BaseURL+"/api/locations/{id}", wrapper.PutApiLocationsId)
	m.HandleFunc("GET "+options.BaseURL+"/api/map/events.geojson", wrapper.GetApiMapEventsGeojson)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/media/{id}", wrapper.DeleteApiMediaId)
	m.HandleFunc("GET "+options.BaseURL+"/api/sources", wrapper.GetApiSources)
	m.HandleFunc("POST "+options.BaseURL+"/api/sources", wrapper.PostApiSources)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/sources/{id}", wrapper.DeleteApiSourcesId)
	m.HandleFunc("GET "+options.BaseURL+"/api/sources/{id}", wrapper.GetApiSourcesId)
	m.HandleFunc("PUT "+options.BaseURL+"/api/sources/{id}", wrapper.PutApiSourcesId)
	m.HandleFunc("GET "+options.BaseURL+"/api/tags", wrapper.GetApiTags)
	m.HandleFunc("POST "+options.BaseURL+"/api/tags", wrapper.PostApiTags)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/tags/{id}", wrapper.DeleteApiTagsId)
	m.HandleFunc("PUT "+options.BaseURL+"/api/tags/{id}", wrapper.PutApiTagsId)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)

	return m
}
